output-dir: '{project-root}/dist'

emit:
  - '@the-dev-tools/spec-lib/protobuf'
  - '@the-dev-tools/spec-lib/tanstack-db'
  - '@the-dev-tools/spec-lib/ai-tools'

options:
  '@the-dev-tools/spec-lib':
    emitter-output-dir: '{output-dir}'
    goPackage: 'github.com/the-dev-tools/dev-tools/packages/spec/dist/buf/go'
    bufTypeScriptPath: '../buf/typescript'
