output-dir: '{project-root}/dist'

emit:
  - '@the-dev-tools/spec-lib/protobuf'
  - '@the-dev-tools/spec-lib/tanstack-db'

options:
  '@the-dev-tools/spec-lib':
    emitter-output-dir: '{output-dir}'
    goPackage: 'the-dev-tools/spec/dist/buf/go'
    bufTypeScriptPath: '../buf/typescript'
